BENCHMARKS = {
    "default": {
        "exception_reduction_pct": 0.3,
        "logistics_optimization_pct": 0.06,
        "inventory_reduction_pct": 0.1,
        "carrying_cost_rate": 0.18,
        "planner_productivity_improvement_pct": 0.25,
        "planner_fully_loaded_cost": 90000.0,
        "implementation_cost": 200000.0,
        "annual_platform_cost": 150000.0,
        "inventory_turns_benchmark": 8.0,
        "planner_fte_per_100m_revenue": 4.0,
    },
    "Automotive": {
        "exception_reduction_pct": 0.35,
        "logistics_optimization_pct": 0.07,
        "inventory_reduction_pct": 0.12,
        "carrying_cost_rate": 0.2,
        "planner_productivity_improvement_pct": 0.3,
        "planner_fully_loaded_cost": 110000.0,
        "implementation_cost": 300000.0,
        "annual_platform_cost": 180000.0,
        "inventory_turns_benchmark": 10.0,
        "planner_fte_per_100m_revenue": 5.0,
    },
    "Retail": {
        "exception_reduction_pct": 0.25,
        "logistics_optimization_pct": 0.05,
        "inventory_reduction_pct": 0.08,
        "carrying_cost_rate": 0.22,
        "planner_productivity_improvement_pct": 0.2,
        "planner_fully_loaded_cost": 80000.0,
        "implementation_cost": 180000.0,
        "annual_platform_cost": 140000.0,
        "inventory_turns_benchmark": 12.0,
        "planner_fte_per_100m_revenue": 3.0,
    },
    "Pharma": {
        "exception_reduction_pct": 0.3,
        "logistics_optimization_pct": 0.06,
        "inventory_reduction_pct": 0.09,
        "carrying_cost_rate": 0.25,
        "planner_productivity_improvement_pct": 0.22,
        "planner_fully_loaded_cost": 120000.0,
        "implementation_cost": 350000.0,
        "annual_platform_cost": 220000.0,
        "inventory_turns_benchmark": 6.0,
        "planner_fte_per_100m_revenue": 6.0,
    },
    "Manufacturing": {
        "exception_reduction_pct": 0.32,
        "logistics_optimization_pct": 0.06,
        "inventory_reduction_pct": 0.1,
        "carrying_cost_rate": 0.2,
        "planner_productivity_improvement_pct": 0.25,
        "planner_fully_loaded_cost": 95000.0,
        "implementation_cost": 250000.0,
        "annual_platform_cost": 160000.0,
        "inventory_turns_benchmark": 9.0,
        "planner_fte_per_100m_revenue": 4.0,
    },
    "Logistics": {
        "exception_reduction_pct": 0.28,
        "logistics_optimization_pct": 0.08,
        "inventory_reduction_pct": 0.07,
        "carrying_cost_rate": 0.18,
        "planner_productivity_improvement_pct": 0.3,
        "planner_fully_loaded_cost": 85000.0,
        "implementation_cost": 220000.0,
        "annual_platform_cost": 170000.0,
        "inventory_turns_benchmark": 11.0,
        "planner_fte_per_100m_revenue": 5.0,
    },
}


def get_benchmarks(industry: str) -> dict:
    i = industry.strip() if industry else ""
    return BENCHMARKS.get(i, BENCHMARKS["default"])